project-name: adam.thebeckmeyers.xyz
base-path: http://adam.thebeckmeyers.xyz/
context:
  static:
    site_subtitle: Based on a true story
    site_url: http://adam.thebeckmeyers.xyz
  dynamic:
    all_pages: session.query(page).all()
    site_author: session.query(author).filter(author.pk == "adam").all()[0]
