project-name: Another Weblog
base-path: http://adam.thebeckmeyers.xyz/
context:
  static:
    site_subtitle: The one and only; the stupendously vain
    site_url: http://adam.thebeckmeyers.xyz
  dynamic:
    all_pages: session.query(page).all()
    site_author: session.query(author).filter(author.pk == "adam").all()[0]
